## Domain mapped to the services
host: search.local

## Canary
canary:
  enabled: false
  weight: 10
  serviceName: search.services-v2.svc.cluster.local

  ## If we only want users to access the canary release based on the header
  ## X-Track: canary instead of weight. If true, weight is ignored.
  onlyMatchHeader: false

## Stable
stable:
  serviceName: search.services-v1.svc.cluster.local
  weight: 90
