## Entrypoint domain
host: search.local

## Canary
canary:
  enabled: false
  weight: 10
  serviceName: search.services-v2.svc.cluster.local

  ## If we only want users to access the canary release based on headers
  match: {}
    ## Only users with cookie 'access=v2' can access the canary release
    # - headers:
    #     cookie:
    #       regex: "^(.*?;)?(access=v2)(;.*)?"

    ## Only users with header 'X-Track: canary' can access the canary release
    # - headers:
    #     x-track:
    #       exact: canary

## Stable
stable:
  serviceName: search.services-v1.svc.cluster.local
  weight: 90
