apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "traffic-manager.fullname" . }}
  labels:
    app: {{ template "traffic-manager.name" . }}
    chart: {{ template "traffic-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.host }}
