apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "traffic-manager.fullname" . }}
  labels:
    app: {{ template "traffic-manager.name" . }}
    chart: {{ template "traffic-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
    - {{ .Values.host }}
  gateways:
    - {{ template "traffic-manager.fullname" . }}
  http:
  {{- if .Values.canary.enabled }}
    {{- if gt (len .Values.canary.match) 0 }}
    - route:
        - destination:
            host: {{ .Values.canary.serviceName }}
      match:
{{ toYaml .Values.canary.match | indent 8 }}

    - route:
    {{- else }}
    - route:
        - destination:
            host: {{ .Values.canary.serviceName }}
          weight: {{ .Values.canary.weight }}
    {{- end }}
  {{- end }}
        - destination:
            host: {{ .Values.stable.serviceName }}
          {{- if and .Values.canary.enabled (eq (len .Values.canary.match) 0) }}
          weight: {{ .Values.stable.weight }}
          {{- end }}
